<?php

	// De esta manera tengo el scope a la funciones que necesito
	require_once 'register-login-controller.php';

	// cargo el array de paises para que me aparezca en el combo de edicion;
	$countries = [
	'AF'=>'Afganistán',
	'AL'=>'Albania',
	'DE'=>'Alemania',
	'AD'=>'Andorra',
	'AO'=>'Angola',
	'AI'=>'Anguilla',
	'AQ'=>'Antártida',
	'SA'=>'Arabia',
  'DZ'=>'Argelia',
	'AR'=>'Argentina',
  'AM'=>'Armenia',
	'AW'=>'Aruba',
	'AU'=>'Australia',
	'AT'=>'Austria',
	'AZ'=>'Azerbaiyán',
	'BS'=>'Bahamas',
	'BH'=>'Bahrein',
	'BD'=>'Bangladesh',
  'BB'=>'Barbados',
	'BE'=>'Bélgica',
	'BZ'=>'Belice',
	'BJ'=>'Benin',
	'BM'=>'Bermudas',
	'BY'=>'Bielorrusia',
	'MM'=>'Birmania',
	'BO'=>'Bolivia',
  'BA'=>'Bosnia y Herzegovina',
	'BW'=>'Botswana',
	'BR'=>'Brasil',
	'BN'=>'Brunei',
	'BG'=>'Bulgaria',
	'BF'=>'Burkina Faso',
	'BI'=>'Burundi',
	'BT'=>'Bután',
	'CV'=>'Cabo Verde',
	'KH'=>'Camboya',
	'CM'=>'Camerún',
	'CA'=>'Canadá',
	'TD'=>'Chad',
	'CL'=>'Chile',
  'CN'=>'China',
	'CY'=>'Chipre',
	'VA'=>'Ciudad del Vaticano (Santa Sede)',
	'CO'=>'Colombia',
	'KM'=>'Comores',
	'CG'=>'Congo',
  'CD'=>'Congo, República Democrática del Congo',
	'KR'=>'Corea',
	'KP'=>'Corea del Norte',
	'CI'=>'Costa de Marfíl',
	'CR'=>'Costa Rica',
	'HR'=>'Croacia (Hrvatska)',
	'CU'=>'Cuba',
	'DK'=>'Dinamarca',
	'DJ'=>'Djibouti',
	'DM'=>'Dominica',
	'EC'=>'Ecuador',
	'EG'=>'Egipto',
	'SV'=>'El Salvador',
	'AE'=>'Emiratos Árabes Unidos',
	'ER'=>'Eritrea',
	'SI'=>'Eslovenia',
	'ES'=>'España',
	'US'=>'Estados Unidos',
  'EE'=>'Estonia',
	'ET'=>'Etiopía',
	'FJ'=>'Fiji',
	'PH'=>'Filipinas',
  'FI'=>'Finlandia',
	'FR'=>'Francia',
	'GA'=>'Gabón',
	'GM'=>'Gambia',
	'GE'=>'Georgia',
	'GH'=>'Ghana',
	'GI'=>'Gibraltar',
	'GD'=>'Granada',
	'GR'=>'Grecia',
	'GL'=>'Groenlandia',
	'GP'=>'Guadalupe',
	'GU'=>'Guam',
	'GT'=>'Guatemala',
	'GY'=>'Guayana',
  'GF'=>'Guayana Francesa',
	'GN'=>'Guinea',
	'GQ'=>'Guinea Ecuatorial',
	'GW'=>'Guinea-Bissau',
	'HT'=>'Haití',
	'HN'=>'Honduras',
	'HU'=>'Hungría',
	'IN'=>'India',
	'ID'=>'Indonesia',
	'IQ'=>'Irak',
	'IR'=>'Irán',
	'IE'=>'Irlanda',
	'BV'=>'Isla Bouvet',
	'CX'=>'Isla de Christmas',
	'IS'=>'Islandia',
	'CK'=>'Islas Cook',
	'KY'=>'Islas Caimán',
	'CC'=>'Islas de Cocos o Keeling',
	'FO'=>'Islas Faroe',
	'HM'=>'Islas Heard y McDonald',
	'FK'=>'Islas Malvinas',
	'MP'=>'Islas Marianas del Norte',
	'MH'=>'Islas Marshall',
	'UM'=>'Islas menores de Estados Unidos',
	'PW'=>'Islas Palau',
	'SB'=>'Islas Salomón',
	'SJ'=>'Islas Svalbard y Jan Mayen',
	'TK'=>'Islas Tokelau',
	'TC'=>'Islas Turks y Caicos',
	'VI'=>'Islas Vírgenes (EEUU)',
	'VG'=>'Islas Vírgenes (Reino Unido)',
	'WF'=>'Islas Wallis y Futuna',
	'IL'=>'Israel',
	'IT'=>'Italia',
	'JM'=>'Jamaica',
	'JP'=>'Japón',
	'JO'=>'Jordania',
	'KZ'=>'Kazajistán',
	'KE'=>'Kenia',
	'KG'=>'Kirguizistán',
	'KI'=>'Kiribati',
  'KW'=>'Kuwait',
	'LA'=>'Laos',
  'LS'=>'Lesotho',
  'LV'=>'Letonia',
	'LB'=>'Líbano',
	'LR'=>'Liberia',
	'LY'=>'Libia',
	'LI'=>'Liechtenstein',
	'LT'=>'Lituania',
	'LU'=>'Luxemburgo',
	'MK'=>'Macedonia, Ex-República Yugoslava de Macedonia',
	'MG'=>'Madagascar',
	'MY'=>'Malasia',
  'MW'=>'Malawi',
	'MV'=>'Maldivas',
	'ML'=>'Malí',
	'MT'=>'Malta',
	'MA'=>'Marruecos',
	'MQ'=>'Martinica',
	'MU'=>'Mauricio',
	'MR'=>'Mauritania',
	'YT'=>'Mayotte',
	'MX'=>'México',
	'FM'=>'Micronesia',
  'MD'=>'Moldavia',
	'MC'=>'Mónaco',
	'MN'=>'Mongolia',
	'MS'=>'Montserrat',
	'MZ'=>'Mozambique',
	'NA'=>'Namibia',
	'NR'=>'Nauru',
	'NP'=>'Nepal',
	'NI'=>'Nicaragua',
	'NE'=>'Níger',
	'NG'=>'Nigeria',
	'NU'=>'Niue',
	'NF'=>'Norfolk',
	'NO'=>'Noruega',
  'NC'=>'Nueva Caledonia',
	'NZ'=>'Nueva Zelanda',
	'OM'=>'Omán',
	'NL'=>'Países Bajos',
	'PA'=>'Panamá',
	'PG'=>'Papúa Nueva Guinea',
	'PK'=>'Paquistán',
	'PY'=>'Paraguay',
	'PE'=>'Perú',
	'PN'=>'Pitcairn',
	'PF'=>'Polinesia Francesa',
	'PL'=>'Polonia',
	'PT'=>'Portugal',
	'PR'=>'Puerto Rico',
	'QA'=>'Qatar',
	'UK'=>'Reino Unido',
	'CF'=>'República Centroafricana',
	'CZ'=>'República Checa',
	'ZA'=>'República de Sudáfrica',
	'DO'=>'República Dominicana',
	'SK'=>'República Eslovaca',
	'RE'=>'Reunión',
	'RW'=>'Ruanda',
	'RO'=>'Rumania',
	'RU'=>'Rusia',
	'EH'=>'Sahara Occidental',
	'KN'=>'Saint Kitts y Nevis',
	'WS'=>'Samoa',
	'AS'=>'Samoa Americana',
	'SM'=>'San Marino',
	'VC'=>'San Vicente y Granadinas',
	'SH'=>'Santa Helena',
	'LC'=>'Santa Lucía',
	'ST'=>'Santo Tomé y Príncipe',
	'SN'=>'Senegal',
	'SC'=>'Seychelles',
	'SL'=>'Sierra Leona',
	'SG'=>'Singapur',
	'SY'=>'Siria',
	'SO'=>'Somalia',
	'LK'=>'Sri Lanka',
	'PM'=>'St Pierre y Miquelon',
	'SZ'=>'Suazilandia',
	'SD'=>'Sudán',
	'SE'=>'Suecia',
	'CH'=>'Suiza',
	'SR'=>'Surinam',
  'TH'=>'Tailandia',
	'TW'=>'Taiwán',
	'TZ'=>'Tanzania',
	'TJ'=>'Tayikistán',
	'TF'=>'Territorios franceses del Sur',
	'TP'=>'Timor Oriental',
	'TG'=>'Togo',
	'TO'=>'Tonga',
	'TT'=>'Trinidad y Tobago',
	'TN'=>'Túnez',
	'TM'=>'Turkmenistán',
  'TR'=>'Turquía',
	'TV'=>'Tuvalu',
	'UA'=>'Ucrania',
	'UG'=>'Uganda',
	'UY'=>'Uruguay',
	'UZ'=>'Uzbekistán',
	'VU'=>'Vanuatu',
	'VE'=>'Venezuela',
	'VN'=>'Vietnam',
  'YE'=>'Yemen',
  'YU'=>'Yugoslavia',
	'ZM'=>'Zambia',
	'ZW'=>'Zimbabue',
	];
	// copiamos el register y cambiamos lo que corresponde
	// Creamos esta variable con Array vacío para que no de error al entrar por GET
	$errorsInEdit = [];

// si venimos por post toma los valores de las variables y las trimea
	if ($_POST) {
		{
			// code...

		// Las variables de persistencia les asigno el valor que vino de $_POST
		$name = trim($_POST['name']);
		$email = trim($_POST['email']);
		$userName = trim($_POST["userName"]);
		$countryEdit = $_POST['country'];
		// La función registerValidate() nos retorna el array de errores que almacenamos en esta variable
		$errorsInEdit = editValidate();
		// Si no hay errores en el registro
		// Cuando no hay errores guardo la imagen y los datos
		//if ( count($errorsInRegister) == 0 ) {
		if ( !$errorsInEdit ) {
			// Guardo la imagen y obtengo el nombre aleatorio creado
			$imgName = saveImage();
			// Creo en $_POST una posición "avatar" para guardar el nombre de la imagen
			$_POST['avatar'] = $imgName;
			// piso al usuario en el archivo JSON, y me devuelve al usuario editado
			$theUser = editUser();

			// graba $theUser en la sesion y lo envia a profile
			login($theUser);
		}
	}
	}
	// require_once 'partials/navbar.php';
?>




	<!-- //Register-Form -->

<!-- ?php require_once 'partials/footer.php'; ?> -->
